//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileGallery
{
    public partial class Default
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// CategoryRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater CategoryRepeater;

        /// <summary>
        /// CategoryNameLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal CategoryNameLiteral;

        /// <summary>
        /// FileCountLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal FileCountLiteral;

        /// <summary>
        /// NoFilesPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel NoFilesPanel;

        /// <summary>
        /// FileListPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel FileListPanel;

        /// <summary>
        /// FileRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater FileRepeater;

        /// <summary>
        /// MarkdownPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MarkdownPanel;

        /// <summary>
        /// MarkdownContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal MarkdownContent;

        /// <summary>
        /// NoMarkdownPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel NoMarkdownPanel;

        /// <summary>
        /// MarkdownEmptyClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal MarkdownEmptyClass;
    }
}